name: Black

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    - name: Install Black
      run: |
        python -m pip install --upgrade pip
        pip install black
        
    - name: Run Black
      run: black . --check --extend-exclude "qtdesigner/"